#!/bin/sh
DAEMON=/usr/bin/python3
SCRIPT=/opt/bosporus/gateway.py
PIDFILE=/var/run/bosporus-gateway.pid

start() {
	printf "Starting bosporus-gateway: "
	start-stop-daemon -S -q -b -m -p $PIDFILE --exec $DAEMON -- $SCRIPT
	[ $? = 0 ] && echo "OK" || echo "FAIL"
}
stop() {
	printf "Stopping bosporus-gateway: "
	start-stop-daemon -K -q -p $PIDFILE
	[ $? = 0 ] && echo "OK" || echo "FAIL"
}
restart() {
	stop
	start
}
case "$1" in
  start) start ;;
  stop) stop ;;
  restart|reload) restart ;;
  *) echo "Usage: $0 {start|stop|restart}"; exit 1 ;;
esac
exit $?
